name: WADAS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - bcrypt==4.2.1
  - fastapi==0.115.2
  - filetype==1.2.0
  - ipykernel==6.29.5
  - keyring==25.4.1
  - onnx==1.16.2
  - opencv==4.10.0
  - pip==24.2
  - pyftpdlib==1.5.10
  - python==3.10.15
  - requests==2.32.3
  - timm==1.0.9
  - torchaudio==2.4.1
  - torchvision==0.19.1
  - validators==0.34.0
  - pymysql==1.1.1
  - sqlalchemy==2.0.34
  - mariadb==1.1.11
  - python-jose==3.3.0
  - mariadb-connector-c=3.4.4
  - pip:
      - cv2-enumerate-cameras==1.1.15
      - intel-npu-acceleration-library==1.4.0
      - pyside6==6.8.0.2
      - PytorchWildlife==1.2.0
      - pytest==8.3.3
      - openvino==2024.5.0
      - ray==2.43.0
      - wadas-runtime==0.1.0
