name: Test
permissions: read-all

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: WADAS
        environment-file: wadas/conda_env_setup.yml
        auto-activate-base: false
    - run: |
        conda info
        conda list
    - name: Login to Hugging Face
      run: |
        huggingface-cli login --token ${{ secrets.WADASDEV_HUGGINGF_AUTH }} --add-to-git-credential
    - name: Run tests
      run: |
        python -m pytest test -sv